# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXK8-MkboXabkBXOBPn9_Fzs9Vaaxk2a
"""

# Recebe dois números do usuário
num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

# Exibe as opções de operação para o usuário
print("\nEscolha uma operação:")
print("1 - Adição")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")

# Recebe a escolha de operação do usuário
escolha = input("Digite o número da operação desejada: ")

# Realiza a operação escolhida e exibe o resultado
if escolha == '1':
    resultado = num1 + num2
    print(f"Resultado da Adição: {resultado}")
elif escolha == '2':
    resultado = num1 - num2
    print(f"Resultado da Subtração: {resultado}")
elif escolha == '3':
    resultado = num1 * num2
    print(f"Resultado da Multiplicação: {resultado}")
elif escolha == '4':
    if num2 != 0:
        resultado = num1 / num2
        print(f"Resultado da Divisão: {resultado}")
    else:
        print("Erro: Divisão por zero não é permitida.")
else:
    print("Opção inválida! Por favor, escolha uma operação válida.")